In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# User guide: oceanicospy

**oceanicospy** is still under construction, but some of its functionalities can be used now. The original and test version are avaliable in the python package index (PyPI).

The test version will be used as a beta version to avoid sporious official versions in PyPI.

# Installing the library: Google Colab

The following command install the test PyPI version which is currently enough for users.

In [ ]:
!pip install --upgrade --index-url https://test.pypi.org/simple/ oceanicospy==0.0.1

Looking in indexes: https://test.pypi.org/simple/
Requirement already satisfied: oceanicospy==0.0.1 in /usr/local/lib/python3.12/dist-packages (0.0.1)

In [ ]:
!pip show oceanicospy

Name: oceanicospy
Version: 0.0.1
Summary: A handle package for most of the programming tools in the research group OCEANICOS
Home-page:
Author: OCEANICOS developer team
Author-email: OCEANICOS developer team <oceanicos_med@unal.edu.co>
License: MIT
Location: /usr/local/lib/python3.12/dist-packages
Requires:
Required-by:

# Global and specific imports

It has to be mentioned that we can use global and specific imports based on what we need from a library. We can use something like this:

In [ ]:
import matplotlib.pyplot as plt

or something specific based on some specific subpackage like: from *package_name.subpackage_name* import *specific module or another subpackage*

In [ ]:
from matplotlib import pyplot as plt

# Understanding the library

We can see the library content importing it or even checking the structure on: https://github.com/oceanicos/oceanicospy/tree/main/oceanicospy

In [ ]:
import oceanicospy

In [ ]:
help(oceanicospy)

Help on package oceanicospy:

NAME
    oceanicospy

PACKAGE CONTENTS
    analysis (package)
    models (package)
    observations (package)
    plots (package)
    retrievals (package)
    utils (package)

FILE
    /usr/local/lib/python3.12/dist-packages/oceanicospy/__init__.py

Each item under the package contents section is a package itself (so-called subpackage). They are described as follows based on their function:

- **analysis**: applying different types of temporal and spectral techniques on oceanographic data.

- **models**: automatizing most of the preprocessing tasks in numerical models such as: SWAN and XBeach.

- **observations**: reading the data recorded by different oceanographic devices available in the research group.

- **plots**:

- **retrievals**: retrieving automatically data from different data sources such as reanalysis, real-time data, etc.

Each subpackage can be accessed using the *dot notation*.

In [ ]:
from oceanicospy.observations import RBR

or using the global import with alias.

In [ ]:
import oceanicospy as ocpy

## analysis subpackage

In [ ]:
from oceanicospy.analysis import *
help(oceanicospy.analysis)

Help on package oceanicospy.analysis in oceanicospy:

NAME
    oceanicospy.analysis

PACKAGE CONTENTS
    climatology
    extremes
    spectral
    spectral_old
    temporal

FILE
    /usr/local/lib/python3.12/dist-packages/oceanicospy/analysis/__init__.py

## models subpackage

In [ ]:
from oceanicospy.models import *
help(oceanicospy.models)

Help on package oceanicospy.models in oceanicospy:

NAME
    oceanicospy.models

PACKAGE CONTENTS
    swanpy (package)
    ww3py (package)
    ww3py_old (package)
    xbeachpy (package)

FILE
    /usr/local/lib/python3.12/dist-packages/oceanicospy/models/__init__.py

## observations subpackage

In [ ]:
from oceanicospy.observations import *
help(oceanicospy.observations)

Help on package oceanicospy.observations in oceanicospy:

NAME
    oceanicospy.observations

PACKAGE CONTENTS
    CTD
    aqualogger
    awac
    bluelog
    pressure_sensor_base
    rbr
    resistive_waterlevel_sensor
    weather_station

FILE
    /usr/local/lib/python3.12/dist-packages/oceanicospy/observations/__init__.py

## retrievals subpackage

In [ ]:
from oceanicospy.retrievals import *
help(oceanicospy.retrievals)

ModuleNotFoundError: No module named 'cdsapi'

# Walkthrough examples

## observations subpackage

Imagine you have to process the data coming from a pressure sensor like RBR or AQUAlogger. You can easily import a class to manipulate those raw data with the library.

Each device is assumed as a object, which means you can instancelize it and then using the methods associated to it.

In [ ]:
from oceanicospy.observations import RBR

In [ ]:
help(RBR)

Help on class RBR in module oceanicospy.observations.rbr:

class RBR(oceanicospy.observations.pressure_sensor_base.BaseLogger)
 |  RBR(directory_path: str, sampling_data: dict)
 |
 |  A sensor-specific reader for RBR .txt files.
 |
 |  Inherits from ``BaseLogger`` and implements methods specific to RBR file formats.
 |
 |  Parameters
 |  ----------
 |  directory_path : str
 |      Path to the directory containing the .txt files.
 |  sampling_data : dict
 |      Dictionary containing information on device installation, including:
 |
 |      - ``start_time``: The start time of the sampling period.
 |      - ``end_time``: The end time of the sampling period.
 |      - ``sampling_rate``: The sampling rate of the device (Hz)
 |      - ``burst_duration``: The duration of each burst (seconds)
 |
 |  Method resolution order:
 |      RBR
 |      oceanicospy.observations.pressure_sensor_base.BaseLogger
 |      abc.ABC
 |      builtins.object
 |
 |  Readonly properties defined here:
 |
 |  first_record_time
 |      See :attr:`BaseLogger.first_record_time`
 |
 |  last_record_time
 |      See :attr:`BaseLogger.last_record_time`
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __abstractmethods__ = frozenset()
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from oceanicospy.observations.pressure_sensor_base.BaseLogger:
 |
 |  __init__(self, directory_path: str, sampling_data: dict)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  get_clean_records(self, detrended: bool = True) -> pandas.core.frame.DataFrame
 |      Processes the raw data by grouping the series per each burst
 |
 |      Parameters
 |      ----------
 |      detrended : bool, optional
 |          If True, applies a linear detrending to the depth data within each burst. Default is ``True``.
 |
 |      Returns
 |      -------
 |      pandas.DataFrame
 |          A cleaned DataFrame with bursts identified by a 'burstId' column.
 |
 |  get_raw_records(self) -> pandas.core.frame.DataFrame
 |      Reads the records file from the device to create a DataFrame containing data.
 |
 |      Returns
 |      -------
 |      pandas.DataFrame
 |          A DataFrame containing the raw data indexed by timestamp.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from oceanicospy.observations.pressure_sensor_base.BaseLogger:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

As it can be seen, the initializer method for the class requires: a directory path and a sampling dict.

The directory path needs to be a string where the .csv or .txt is hosted. The sampling data is ...

In [ ]:
directory = '/content/drive/MyDrive/CampoSAI_05_2025/DATOS/BRUTOS/RBR/RBR2_SoundBay_OutBarrier_serial96/234696_20250520_1727'
sampling_data = dict(start_time=datetime(2025, 5, 9, 14, 0, 0),
                     end_time=datetime(2025, 5, 19, 8, 0, 0),
                     sampling_freq=2,
                     anchoring_depth=2.3,
                     sensor_height=2.2,
                     burst_length_s=1024)

Once the input parameters are defined they can be used to instance the class.

In [ ]:
RBR_SB = RBR(directory, sampling_data)

We can check the object type of the previous object:

In [ ]:
type(RBR_SB)

oceanicospy.observations.rbr.RBR

In [ ]:
df_raw_RBR_SB = RBR_SB.get_raw_records()

In [ ]:
df_raw_RBR_SB

                         pressure[bar]  depth[m]
date
2025-05-09 14:00:00.000       1.599715  5.816827
2025-05-09 14:00:00.500       1.608578  5.904731
2025-05-09 14:00:01.000       1.626571  6.083195
2025-05-09 14:00:01.500       1.641845  6.234686
2025-05-09 14:00:02.000       1.646976  6.285586
...                                ...       ...
2025-05-19 07:59:58.000       1.619397  6.012037
2025-05-19 07:59:58.500       1.618974  6.007845
2025-05-19 07:59:59.000       1.620157  6.019578
2025-05-19 07:59:59.500       1.621691  6.034791
2025-05-19 08:00:00.000       1.623387  6.051617

[1684801 rows x 2 columns]

We can also use some object properties if they are defined.

In [ ]:
RBR_SB.first_record_time

'2025-05-09 06:00:00.000'

In [ ]:
RBR_SB.last_record_time

'2025-05-20 16:58:00.500'

Notice that the methods usually start with a verb to describe the job they are doing on the object.

In [ ]:
df_clean_RBR_SB = RBR_SB.get_clean_records()

In [ ]:
df_clean_RBR_SB

                         pressure[bar]  depth[m]  burstId    eta[m]
date
2025-05-09 14:00:00.000       1.599715  5.816827        1 -0.116576
2025-05-09 14:00:00.500       1.608578  5.904731        1 -0.028669
2025-05-09 14:00:01.000       1.626571  6.083195        1  0.149798
2025-05-09 14:00:01.500       1.641845  6.234686        1  0.301293
2025-05-09 14:00:02.000       1.646976  6.285586        1  0.352197
...                                ...       ...      ...       ...
2025-05-19 07:59:58.000       1.619397  6.012037      234 -0.024591
2025-05-19 07:59:58.500       1.618974  6.007845      234 -0.028777
2025-05-19 07:59:59.000       1.620157  6.019578      234 -0.017036
2025-05-19 07:59:59.500       1.621691  6.034791      234 -0.001816
2025-05-19 08:00:00.000       1.623387  6.051617      235  0.000000

[1684801 rows x 4 columns]

## analysis subpackage

In [ ]:
from oceanicospy.analysis import WaveSpectralAnalyzer

In [ ]:
SpectralAnalyzer = WaveSpectralAnalyzer(df_clean_RBR_SB,sampling_data)